version: 2
env:
  - CGO_ENABLED=0
builds:
  - binary: tflint-ruleset-lucid-conventions
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_386
      - linux_amd64
      - linux_arm
      - linux_arm64
      - windows_386
      - windows_amd64
    hooks:
      post:
        - mkdir -p ./dist/raw
        - cp "{{ .Path }}" "./dist/raw/tflint-ruleset-lucid-conventions_{{ .Os }}_{{ .Arch }}"
archives:
  - id: zip
    name_template: "tflint-ruleset-lucid-conventions_{{ .Os }}_{{ .Arch }}"
    formats:
      - zip
    files:
      - none*
checksum:
  name_template: 'checksums.txt'
  extra_files:
    - glob: ./dist/raw/*
signs:
  - artifacts: checksum
    args: ["--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]
release:
  github:
